config/routes.rb
Dom::Application.routes.draw do
  get "admin/index"
  devise_for :users

  scope '/admin' do
  resources :devices
  resources :room_categories
  resources :categories
  resources :rooms
end

  get "main/index"
  root "main#index"

get '/room/:id', to: 'main#room', as: 'main_room'
get '/category/:id', to: 'main#category', as: 'main_category'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_action :prepare_sidebar

  def index
  end

  def room
  	@room =Room.find(params[:id])
  	end

  def category
  	@category =Category.find(params[:id])
  end

  private 
  def prepare_sidebar
  	@rooms = Room.all
  	@categories = Category.all

  end


end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_sidebar.html.erb

  <div class="span3">
             <div class="well sidebar-nav">
  
    <ul class="nav nav-list">
 <h1>Pokoje</h1>
        <% @rooms.each do |room| %>
    <p> <%= link_to room.name, main_room_path(room)  %> </p>
    <% end %>
<h1>Kategorie</h1>
    <% @categories.each do |cat| %>
    <p> <%= link_to cat.name , main_category_path(cat) %> </p>
    <% end %>



              </ul>
            </div><!--/.well -->
          </div><!--/span-->

app/views/main/category.html.erb
<h2><%= @category.name %></h2>
<% @category.rooms.each do |room|  %>
  <p>
    <h4>
      <%= room.name %>
    </h4>
    <% room.room_categories.where(category_id: @category.id).each do |room_cat| %>
      <% room_cat.devices.each do |device| %>
        <%= device.name %>
        <p>
          <%= check_box_tag "switch_#{device.id}", device.on, device.on %>
        </p>
      <% end %>
      <hr>
    <% end %>
<% end %>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/main/room.html.erb
<h2><%= @room.name %></h2>
<% @room.categories.each do |cat|  %>
  <p><h4><%= cat.name %>
    </p>
  </h4>
  <% cat.room_categories.where(room_id: @room.id).each do |room_cat| %>
    <% room_cat.devices.each do |device| %>
      <%= device.name %>
      <p>
         <%= check_box_tag "switch_#{device.id}", device.on, device.on %>
      </p>
    <% end %>
    <hr>
  <% end %>
<% end %>